apiVersion: v1
kind: Pod
metadata:
  labels:
    test: reviews
  name: reviews
spec:
  containers:
    - name: container-reviews-java
      image: docker.io/istio/examples-bookinfo-reviews-v1:1.16.4
      imagePullPolicy: IfNotPresent
      env:
      - name: LOG_DIR
        value: "/tmp/logs"
      ports:
      - containerPort: 9080
      volumeMounts:
      - name: tmp
        mountPath: /tmp
      - name: wlp-output
        mountPath: /opt/ibm/wlp/output
      securityContext:
        runAsUser: 1000

  volumes:
    - name: wlp-output
      emptyDir: {}
    - name: tmp
      emptyDir: {}