apiVersion: v1
kind: Pod
metadata:
  labels:
    test: details
  name: details
spec:
  containers:
    - name: details-ruby
      image: docker.io/istio/examples-bookinfo-details-v1:1.16.4
      imagePullPolicy: IfNotPresent
      ports:
      - containerPort: 9080
      