apiVersion: v1
kind: Pod
metadata:
  labels:
    test: productpage
  name: productpage
spec:
  containers:
    - name: container-flask
      image: docker.io/istio/examples-bookinfo-productpage-v1:1.16.4
      imagePullPolicy: IfNotPresent
      ports:
      -  containerPort: 9080
      resources:
        limits:
          cpu: 100m
          memory: 200Mi
        requests:
          cpu: 100m
          memory: 200Mi


      volumeMounts:
        - name: tmp
          mountPath: /tmp
  volumes:
  - name: tmp
    emptyDir: {}